import type { Metadata } from "next";
import { Baloo_Bhai_2 } from "next/font/google";
import "./globals.css";

const balooBhai = Baloo_Bhai_2({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-baloo',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Learners let's go",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${balooBhai.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout


